__version__:
  serializer: 1
  data: 17
Settings:
  Acquisitions:
    - Acquisition:
        Aperture: 5.7
        Brightness: 1.8
        ExposureTime: 41667
        Gain: 1
    - Acquisition:
        Aperture: 2.38
        Brightness: 1.8
        ExposureTime: 40000
        Gain: 1
    - Acquisition:
        Aperture: 1.83
        Brightness: 1.8
        ExposureTime: 25000
        Gain: 1
  Diagnostics:
    Enabled: no
  Experimental:
    Engine: stripe
  Processing:
    Color:
      Balance:
        Blue: 1
        Green: 1
        Red: 1
      Experimental:
        Mode: automatic
      Gamma: 0.8
    Filters:
      Cluster:
        Removal:
          Enabled: yes
          MaxNeighborDistance: 4
          MinArea: 3
      Experimental:
        ContrastDistortion:
          Correction:
            Enabled: yes
            Strength: 1
          Removal:
            Enabled: no
            Threshold: 1
        HoleFilling:
          Enabled: no
          HoleSize: 0.2
          Strictness: 2
      Noise:
        Removal:
          Enabled: yes
          Threshold: 4
      Outlier:
        Removal:
          Enabled: yes
          Threshold: 8
      Reflection:
        Removal:
          Enabled: yes
          Experimental:
            Mode: global
      Smoothing:
        Gaussian:
          Enabled: yes
          Sigma: 2.75
  RegionOfInterest:
    Box:
      Enabled: no
      Extents: [-300, -13]
      PointA: [103.424538, 28.3209038, 984.564392]
      PointB: [277.028229, 99.7504272, 941.085571]
      PointO: [101.321663, 92.0581589, 939.474915]
    Depth:
      Enabled: no
      Range: [300, 1300]
